services:
  - type: web
    name: sign-language-web
    env: python
    buildCommand: "python --version && pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: PORT
        value: 10000
